# This file is part of LilyPond, the GNU music typesetter.
#
# Copyright (C) 2020--2020  Jonas Hahnfeld <hahnjo@hahnjo.de>
#
# LilyPond is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# LilyPond is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with LilyPond.  If not, see <http://www.gnu.org/licenses/>.

stages:
  - build
  - test
  - documentation

# Source files are checked out freshly for each job. This leads to the situation
# that make considers the artifacts outdated and rebuilds LilyPond from scratch.
# $TOUCH_BUILD contains the command needed to touch the downloaded build files.
variables:
  CONFIGURE_FLAGS: "--ci"
  TOUCH_BUILD: "for d in python scripts flower lily mf; do make -C $$d --touch all; done"

# An additional variable not set here but used below is $MAKE_FLAGS. This can
# be set per runner and allows to enable parallel builds. For example, set its
# value to "-j4 CPU_COUNT=4" in order to speed up the build.

build:ubuntu-16.04:
  stage: build
  image: registry.gitlab.com/lilypond/lilypond/ci/ubuntu-16.04:20200829
  interruptible: true
  rules:
    - if: $CI_COMMIT_BRANCH == "stable/2.22"
    - if: $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "web"
  script:
    - mkdir build && cd build
    - ../autogen.sh $CONFIGURE_FLAGS
    - make $MAKE_FLAGS
    - rm -rf Documentation/out out/lybook-db
  artifacts:
    untracked: true
    expire_in: 1 week

test:ubuntu-16.04:
  stage: test
  image: registry.gitlab.com/lilypond/lilypond/ci/ubuntu-16.04:20200829
  interruptible: true
  rules:
    - if: $CI_COMMIT_BRANCH == "stable/2.22"
    - if: $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "web"
  dependencies: [ "build:ubuntu-16.04" ]
  script:
    - cd build
    - sh -c "$TOUCH_BUILD" >/dev/null
    - make $MAKE_FLAGS test
  artifacts:
    name: "logs"
    when: on_failure
    expire_in: 1 week
    paths:
      - "**/*.fail.log"

doc:ubuntu-16.04:
  stage: documentation
  image: registry.gitlab.com/lilypond/lilypond/ci/ubuntu-16.04:20200829
  interruptible: true
  rules:
    - if: $CI_COMMIT_BRANCH == "stable/2.22"
    - if: $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "web"
  dependencies: [ "build:ubuntu-16.04" ]
  script:
    - cd build
    - sh -c "$TOUCH_BUILD" >/dev/null
    - make $MAKE_FLAGS doc
  artifacts:
    name: "logs"
    when: on_failure
    expire_in: 1 week
    paths:
      - "**/*.fail.log"
